### PR TITLE
Windows bugs fix and other enhancements.

### PR DESCRIPTION
**Pull request by cparke2**
Bug fixes for Windows platform, moved hotkey to Ctrl+Alt+T, also updated command to toggle between test and source code.

### CODE REVIEW

**Comment by eskimoblood** [comment]
First of all thanks for your help. Seems like your changes don't break on Mac. The only thing that does not work as expected is the jump from test to file when `config.testFileExtension` is set. So in my case the test file is named `test/someFile.spec.js` and it jumps `/src/someFile.spec.js`. This is caused by the `name` function. Seems like we need to test if it is a test like this:

```
const isTestModule = ({ uri, workSpaceUri, config }) => {
    const path = uri.fsPath.replace(workSpaceUri.fsPath, '')
    return path.startsWith(slashChar + config.testFolder)
}
const name = (uri: Uri, workSpaceUri: Uri, config) => {
    const p = pathFromUri(uri)
    const isTest = isTestModule({ uri, workSpaceUri, config })
    return p
        .basename(isTest ? config.testFileExtension : p.extname())
        .concat(isTest ? p.extname() : config.testFileExtension)
}
```

**Comment by cparke2** [comment]
Yes, that was not apparent to me, as we use testFileExtension = '.js' :-)

At any rate, I applied your suggested changes to my local copy, and while that works with '.spec.js' as the test extension when using absolute paths but not for relative paths!  There is also a bigger problem here: how does the extension know what the normal source file extension is supposed to be when switching from test to source?

Accordingly, I've added a new commit to this pull request adding "sourceFileExtension" into the config and made further changes to fix the handling of testFileExtension that work in both relative and absolute extension.  This should all work on Mac, however I have not tested there nor updated the test modules.  Take another look, please.

Pull request updated accordingly...

**Comment by cparke2** [comment]
I don't know or use TypeScript, so I have been manually transferring my
changes from JavaScript to TypeScript using what appeared to be the right
syntax, but without being able to compile and test it, so that's how that
happened.

Yes, I'll update that issue and the Readme today.  Now that we have
SourceFileExtension, may also want to add a check to block jump/generation
on non-JS files, produces an error or meaningless test module right now,
what do you think?

>

**Comment by eskimoblood** [comment]
Thanks again for your help. If you have other ideas to improve the extension feel free to add another pull request.

**Comment by eskimoblood** [comment]
@cparke2 I've published a new version of the extension.

**Pull request merged**
